//
//  Questions.swift
//  DnD_Alignment_test
//
//  Created by Calvin Lee on 2023/5/19.
//

//建立一個新的swift file來存放問題、選項、陣營，及對應分數的資料
import Foundation

struct Question {
    let questionContent: String
    var choices: [Choice]
}

/*    這邊設了三個常數:
      content是要選項的資訊;
      type是每個選項有自己對應到的陣營;
      選項中的陣營對應的分數也不同 */
struct Choice {
    let content: String
    let type: Type
    let score: Int
}

/*    陣營的方式是用列舉(enumerate)去列出6種，
      會這樣主要是之後再用switch去判斷及抓分數時使用 */
enum Type {
    case Good, GEN, Evil, Law, LCN, Chaos
    }
    

// 陣列資訊範例如下
var questions = [
    Question(questionContent: "1. 长辈在家族中公开反对你，你会：",
             choices: [Choice(content: "接受批评，改变方法.", type: .Good, score:2),
                       Choice(content: "尝试与长辈妥协，用折衷的方法.", type: .Good, score:1),
                       Choice(content: "忽略长辈的轻蔑，诽谤他们.", type: .Evil, score:1),
                       Choice(content: "千方百计使他们收声.",  type: .Evil, score:2)] ),
    Question(questionContent: "2. 你会放弃一个前途无量的职业来帮忙解决家庭的燃眉之急吗？?",
             choices: [Choice(content: "不用想，肯定会.", type: .Good, score:2),
                       Choice(content: "会，但有点不情愿.", type: .Good, score:1),
                       Choice(content: "除非我肯定我会很快重回工作岗位.", type: .GEN, score:1),
                       Choice(content: "不会.", type: .GEN, score:2)] ),
    Question(questionContent: "3. 你会为了前途而背叛家人吗？",
             choices: [Choice(content: "会，不带一点罪恶感.", type: .Evil, score: 2),
                       Choice(content: "会，只要我能秘密行事.", type: .Evil, score: 1),
                       Choice(content: "我会抗拒这诱惑.", type: .GEN, score: 1),
                       Choice(content: "我认为这个主意极为可恨.", type: .GEN, score: 2)] ),
    Question(questionContent: "4. 你尊敬一家之主吗？",
             choices: [Choice(content: "他们的言语指导着我的行动.", type: .Law, score: 2),
                       Choice(content: "他们是我的榜样.", type: .Law, score: 1),
                       Choice(content: "他们通常都与我无关.",  type: .Chaos, score: 1),
                       Choice(content: "我当他们透明.", type: .Chaos, score: 2)] ),
    Question(questionContent: "5. 如果家族要你与一个令人作呕的家伙结婚，你会：",
             choices: [Choice(content: "听从安排，为能帮助家族而自豪.", type: .Law, score: 2),
                       Choice(content: "会，但强颜欢笑.", type: .Law, score: 1),
                       Choice(content: "巧妙地抗婚.", type: .LCN, score: 1),
                       Choice(content: "逃跑.", type: .LCN, score: 2)] ),
    Question(questionContent: "6. 有一位家人疏远了你。在他弥留之际，他想与你和解。你会：",
             choices: [Choice(content: "与他谈谈，但坚守立场.", type: .Chaos, score: 2),
                       Choice(content: "不跟他说话.", type: .Chaos, score: 1),
                       Choice(content: "不计前嫌敞开心扉地讨论前事.", type: .LCN, score: 1),
                       Choice(content: "积极进行和解，并留心听他的遗言.", type: .LCN, score: 2)] ),
    Question(questionContent: "7. 一个位高权重的腐败法官允诺如果你能作对你朋友不利的假证，他便给你一大笔钱。你会：",
             choices: [Choice(content: "照做，然后拿钱.", type: .Evil, score: 2),
                       Choice(content: "拿钱照做，但尽量使证词显得无力.", type: .Evil, score: 2),
                       Choice(content: "拒绝.", type: .Good, score: 1),
                       Choice(content: "不管结果如何，都站在朋友那一边.", type: .Good, score: 2)] ),
    Question(questionContent: "8. 你会亲近朋友，还是与大部分人保持一段距离以保安全？",
             choices: [Choice(content: "我有一大群密友.", type: .Good, score: 2),
                       Choice(content: "我有些密友.", type: .Good, score: 1),
                       Choice(content: "我有几个密友.", type: .GEN, score: 1),
                       Choice(content: "我会与人保持距离.", type: .GEN, score: 2)] ),
    Question(questionContent: "9. 你背叛过朋友吗？",
             choices: [Choice(content: "我干过不止一次，有时也能逃避惩罚.", type: .Evil, score: 2),
                       Choice(content: "我只干过那么一次.", type: .Evil, score: 1),
                       Choice(content: "我曾被怂恿过这么做，但从未做过.", type: .GEN, score: 1),
                       Choice(content: "我从未考虑过这种事.", type: .GEN, score: 2)] ),
    Question(questionContent: "10. 你怎么看待“执子之手，与子偕老”这类对爱人的终生承诺？",
             choices: [Choice(content: "我曾有过或正渴望着这么一段罗曼史.", type: .Law, score: 2),
                       Choice(content: "这种罗曼史挺理想的，如果能成功的话.", type: .Law, score: 1),
                       Choice(content: "我担心我会错过其他人对我的爱.", type: .Chaos, score: 1),
                       Choice(content: "作茧自缚？真是天大的错误.", type: .Chaos, score: 2)] ),
    Question(questionContent: "11. 朋友借了你钱，你会要他们还吗？",
             choices: [Choice(content: "会，而且写好借据，不得抵赖.", type: .Law, score: 2),
                       Choice(content: "会，但期限上会宽松些.", type: .Law, score: 1),
                       Choice(content: "不会，尽管还了会更好.", type: .LCN, score: 1),
                       Choice(content: "不会，他们欠我一个人情.", type: .LCN, score: 2)] ),
    Question(questionContent: "12. 你仍与儿时玩伴保持联络吗？",
             choices: [Choice(content: "是的，我们定期通信.", type: .LCN, score: 2),
                       Choice(content: "是的，我们努力保持联络.", type: .LCN, score: 1),
                       Choice(content: "不会，我经常搬家.", type: .Chaos, score: 1),
                       Choice(content: "不会，我不再与他们有共同之处.", type: .Chaos, score: 2)] ),
    Question(questionContent: "13. 你会花时间和金钱在集体上吗？",
             choices: [Choice(content: "会，我会优先考虑集体的需要.", type: .Good, score: 2),
                       Choice(content: "如果我的需求被满足的话，我会尽我所能.", type: .Good, score: 1),
                       Choice(content: "不会，我没钱也不闲.", type: .GEN, score: 1),
                       Choice(content: "不会，花时间和金钱在集体上是一种浪费.", type: .GEN, score: 2)] ),
    Question(questionContent: "14. 集体面临被侵害的威胁，你会：",
             choices: [Choice(content: "保卫它直至自己的最后一口气.", type: .Good, score: 2),
                       Choice(content: "和残存同伴构筑防御.", type: .Good, score: 1),
                       Choice(content: "一看到势头不对就逃跑.", type: .Evil, score: 1),
                       Choice(content: "与入侵者达成协议，成为间谍.", type: .Evil, score: 2)] ),
    Question(questionContent: "15. 如果你受伤了，需要急救，你的同伴愿意帮助你吗？",
             choices: [Choice(content: "会的，因为他们知道我也会为他们做同样的事.", type: .GEN, score: 2),
                       Choice(content: "会的，因为我很受欢迎.", type: .GEN, score: 1),
                       Choice(content: "可能不会，因为我不受信任.", type: .Evil, score: 1),
                       Choice(content: "肯定不会，我在集体中树敌了.", type: .Evil, score: 2)] ),
    Question(questionContent: "16. 你尊重集体的规章和领袖吗？",
             choices: [Choice(content: "毋庸置疑，是的.", type: .Law, score: 2),
                       Choice(content: "是的，总的来说他们是最佳的管理方式.", type: .Law, score: 1),
                       Choice(content: "当它适合我时，我才会。儘管有些规章我并不认同.", type: .Chaos, score: 1),
                       Choice(content: "我不关心他们；他们拿我没辙.", type: .Chaos, score: 2)] ),
    Question(questionContent: "17. 同伴回避你，或嘲笑你吗？",
             choices: [Choice(content: "是的，这些井底之蛙不会理解超规格的人.", type: .Chaos, score: 2),
                       Choice(content: "有些会，因为并不是所有人都认同我.", type: .Chaos, score: 1),
                       Choice(content: "不会，我看起来一切正常.", type: .LCN, score: 1),
                       Choice(content: "不会，我就是集体中的正常人的标准.", type: .LCN, score: 2)] ),
    Question(questionContent: "18. 你当官会为民作主，或者希望代表集体的意志吗？",
             choices: [Choice(content: "做这种事是我所乐意接受的荣誉.", type: .Law, score: 2),
                       Choice(content: "当然。这是每个人的义务.", type: .Law, score: 1),
                       Choice(content: "不会，除非无人能接手此事.", type: .LCN, score: 1),
                       Choice(content: "不会，我不想为集体利益负责.", type: .LCN, score: 2)] ),
    Question(questionContent: "19. 你的国家闹饥荒，你会：",
             choices: [Choice(content: "与其他人共享自己有的食物.", type: .Good, score: 2),
                       Choice(content: "自己吃尽可能少，余下的给其他人.", type: .Good, score: 1),
                       Choice(content: "偷取自己生存所需食物.", type: .Evil, score: 1),
                       Choice(content: "偷取尽可能多的食物，然后高价卖出.", type: .Evil, score: 2)] ),
    Question(questionContent: "20. 给你足够的钱，你会往国王的酒中下毒吗？",
             choices: [Choice(content: "会，类似的事我干过了.", type: .Evil, score: 2),
                       Choice(content: "如果我能逃避惩罚的话，我会的.", type: .Evil, score: 1),
                       Choice(content: "不会，尽管我觉得这一大笔钱很诱人.", type: .GEN, score: 1),
                       Choice(content: "不会，而且我会叫国王小心这个阴谋.", type: .GEN, score: 2)] ),
    Question(questionContent: "21. 瘟疫传遍你的国家，你会：",
             choices: [Choice(content: "接下寻求解药的危险任务.", type: .Good, score: 2),
                       Choice(content: "尽力治好病人.", type: .Good, score: 1),
                       Choice(content: "避免接触到病人.", type: .GEN, score: 1),
                       Choice(content: "逃离国家.", type: .GEN, score: 2)] ),
    Question(questionContent: "22. 你尊重领主的法律权威吗？",
             choices: [Choice(content: "是的，皇上萬歲萬歲萬萬歲！", type: .Law, score: 2),
                       Choice(content: "是的，我们的统治者大体上是公平、公正的.", type: .Law, score: 1),
                       Choice(content: "不会，统治者还不是人一个！", type: .Chaos, score: 1),
                       Choice(content: "不会，权力必定导致腐化.", type: .Chaos, score: 2)] ),
    Question(questionContent: "23. 给你一笔稳赚的生意，你会为敌国做间谍吗？",
             choices: [Choice(content: "会，因为我的国家早已任人鱼肉.", type: .Chaos, score: 2),
                       Choice(content: "会，因为国家机密对我无关紧要.", type: .Chaos, score: 1),
                       Choice(content: "不会，我会被抓的.", type: .LCN, score: 1),
                       Choice(content: "不会，我不会辜负国家对我的信任.", type: .LCN, score: 2)] ),
    Question(questionContent: "24. 你依靠政府来建立社会契约和保障所有权吗？",
             choices: [Choice(content: "是的，因为维护法律比任何个人争执重要.", type: .Law, score: 2),
                       Choice(content: "是的，因为法庭就是为了解决这种争执而设立的.", type: .Law, score: 1),
                       Choice(content: "你在开玩笑吗？政府连路都不会铺.", type: .LCN, score: 1),
                       Choice(content: "绝对不会，如果我自己不能保护个人所有，我就无权拥有它.", type: .LCN, score: 2)] ),
    Question(questionContent: "25. 如果你入狱了，你会伤害或杀死其他人而脱狱吗？",
             choices: [Choice(content: "会，服刑这么多年等于锁住自己.", type: .Evil, score: 2),
                       Choice(content: "会，在犯事时便已知道这风险了.", type: .Evil, score: 1),
                       Choice(content: "不会，除非只造成容易愈合的小伤.", type: .GEN, score: 1),
                       Choice(content: "不会，那些守卫只是在尽本分而已.", type: .GEN, score: 2)] ),
    Question(questionContent: "26. 你接受贵族有权恶劣对待手下的仆人吗？",
             choices: [Choice(content: "是的，很幸运，贵族们投了个好胎.", type: .GEN, score: 2),
                       Choice(content: "是的，有时要靠吓，他们才肯干活.", type: .GEN, score: 1),
                       Choice(content: "不会，贵族应仁慈地统治.", type: .Good, score: 1),
                       Choice(content: "任何人都无权恶劣对待别人。以上。.", type: .Good, score: 2)] ),
    Question(questionContent: "27. 你意外地犯罪了，你会：",
             choices: [Choice(content: "认罪，并向受害者赔偿.", type: .Good, score: 2),
                       Choice(content: "认罪，向法官请求宽大处理.", type: .Good, score: 1),
                       Choice(content: "隐瞒自己的涉案事实，必要时说谎.", type: .Evil, score: 1),
                       Choice(content: "嫁祸于人.", type: .Evil, score: 2)] ),
    Question(questionContent: "28. 如果犯罪了，你会认罪吗？",
             choices: [Choice(content: "会，因为我有这个责任.", type: .Law, score: 2),
                       Choice(content: "会，因为我会因此获得轻判.", type: .Law, score: 1),
                       Choice(content: "不会，我会等到检察官证明我有罪.", type: .LCN, score: 1),
                       Choice(content: "不会，我会证明我“无罪”的.", type: .LCN, score: 2)] ),
    Question(questionContent: "29. 如果可能被惩罚，你会表明一个革命性的政见吗？",
             choices: [Choice(content: "会，我宁愿受罚也不愿保持沉默.", type: .Chaos, score: 2),
                       Choice(content: "会，总要有人说真话.", type: .Chaos, score: 1),
                       Choice(content: "不会，尽管私底下我会对朋友说.", type: .LCN, score: 1),
                       Choice(content: "不会，不值得为政治费神.", type: .LCN, score: 2)] ),
    Question(questionContent: "30. 旅行时，你目击了一场袭击。你被传去作证，这会非常耽误你的行程。你会：",
             choices: [Choice(content: "连夜溜走，避免作证.", type: .Chaos, score: 2),
                       Choice(content: "说自己什么也没看到.", type: .Chaos, score: 1),
                       Choice(content: "勉强留下，作证，然后离开.", type: .Law, score: 1),
                       Choice(content: "留下直至结案所需证供足够.", type: .Law, score: 2)] ),
    Question(questionContent: "31. 财富的最大用途是什么？",
             choices: [Choice(content: "帮助穷人和不幸的人.", type: .Good, score: 2),
                       Choice(content: "满足亲朋戚友需要.", type: .Good, score: 1),
                       Choice(content: "让自己达到人生巅峰.", type: .Evil, score: 1),
                       Choice(content: "不仅达到巅峰，还要阻止别人超过自己.", type: .Evil, score: 2)] ),
    Question(questionContent: "32. 遇到乞丐，你会：",
             choices: [Choice(content: "慷慨地给钱.", type: .Good, score: 2),
                       Choice(content: "恰到好处地给钱.", type: .Good, score: 1),
                       Choice(content: "只给我认为无所谓的钱，至多一两块.", type: .GEN, score: 1),
                       Choice(content: "视而不见.", type: .GEN, score: 2)] ),
    Question(questionContent: "33. 通过魔法，你可以使村里的商人们以为你的铜币是金币。你会这样做吗？",
             choices: [Choice(content: "会，而且我还要尽可能地消费.", type: .Evil, score: 2),
                       Choice(content: "会，但只骗富商.", type: .Evil, score: 1),
                       Choice(content: "不会，风险太大了.", type: .GEN, score: 1),
                       Choice(content: "不会，商人也要养家糊口啊.", type: .GEN, score: 2)] ),
    Question(questionContent: "34. 你有两份工作可供选择。一份酬劳更多，另一份较稳定。你会选哪一份？",
             choices: [Choice(content: "肯定是更赚钱的那份；稳定的工作听上去像苦差事.", type: .LCN, score: 2),
                       Choice(content: "可能是前者，尽管我会看看后者干些什么.", type: .LCN, score: 1),
                       Choice(content: "后者，除非前者赚的钱多到吓死人.", type: .Law, score: 1),
                       Choice(content: "肯定是稳定的那份，因为我有长远的计划.", type: .Law, score: 2)] ),
    Question(questionContent: "35. 最佳的致富途径是什么？",
             choices: [Choice(content: "这关乎天时地利，还有一时运气.", type: .Chaos, score: 2),
                       Choice(content: "灵活变通会有更多机会.", type: .Chaos, score: 1),
                       Choice(content: "按照一个有适度风险的长期计划来做.", type: .Law, score: 1),
                       Choice(content: "努力工作，坚持不懈.", type: .Law, score: 2)] ),
    Question(questionContent: "36. 如果你接手一项工作，尽管它会很危险，你会努力完成吗？",
             choices: [Choice(content: "会，我说话算数.", type: .LCN, score: 2),
                       Choice(content: "会，因为人家会认为我信得过，这很好.", type: .LCN, score: 1),
                       Choice(content: "你可以赌我会否爽约.", type: .Chaos, score: 1),
                       Choice(content: "如果这不是什么好差事，那算了吧.", type: .Chaos, score: 2)] )
    ]
 
 
